name: Tourism MLOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  register-dataset:
    runs-on: ubuntu-latest
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install huggingface_hub

      - name: Register dataset on Hugging Face
        run: |
          python tourism_project/model_building/data_register.py

  data-prep:
    runs-on: ubuntu-latest
    needs: register-dataset   # Run only after dataset registration succeeds
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn huggingface_hub

      - name: Run data preparation
        run: |
          python tourism_project/model_building/prep.py

  model-training:
    runs-on: ubuntu-latest
    needs: data-prep   # Run only after data-prep succeeds
    env:
      HF_TOKEN: ${{ secrets.HF_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install scikit-learn xgboost mlflow huggingface_hub

      - name: Train and log model
        run: |
          python tourism_project/model_building/train.py

 deploy-hosting:
    runs-on: ubuntu-latest
    needs: [model-traning,data-prep,register-dataset]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install -r tourism_project/requirements.txt
      - name: Push files to Frontend Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: python tourism_project/hosting/hosting.py
  
